# Generated by Django 2.2.24 on 2022-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0007_auto_20170111_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
