# Generated by Django 2.2.24 on 2023-11-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0008_increase_max_length_of_forum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='images',
            field=models.IntegerField(blank=True, default=0, verbose_name='Images count'),
        ),
    ]
